import { Box } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import { Data } from '../components/Data';
import { Map } from '../components/Map';
import { TitleBar } from '../components/TitleBar';

export type WildFire = {
  location: string;
  chance: number;
  temp: number;
  humidity: number;
};

export const WildFireContext = React.createContext<WildFire[]>([]);

const Home: NextPage = () => {
  const defaultData: WildFire[] = [
    {
      chance: 0.3,
      humidity: 0.37,
      location: 'Los Angeles',
      temp: 36,
    },
    {
      chance: 0.3,
      humidity: 0.37,
      location: 'Pomona',
      temp: 36,
    },
    {
      chance: 0.3,
      humidity: 0.37,
      location: 'Pasadena',
      temp: 36,
    },
  ];
  return (
    <WildFireContext.Provider value={defaultData}>
      <div style={{ height: '100vh' }}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Box
          sx={{
            height: '100%',
            width: '100%',
            display: 'flex',
            flexDirection: 'column',
          }}
        >
          <TitleBar />
          <Box sx={{ flex: '1 1' }}>input</Box>
          <Box
            sx={{
              flex: '4 4',
              height: '80%',
              width: '100%',
              display: 'flex',
              flexDirection: 'row',
            }}
          >
            <Map />
            <Box sx={{ flex: '1 1' }}>
              <Data />
            </Box>
          </Box>
        </Box>
      </div>
    </WildFireContext.Provider>
  );
};

export default Home;
